### ISSUE TITLE
Bugbash doc

### ISSUE THREAD

**Issue by andxu** [andxu/andy_doc#1]
1. download the latest azure cli(version 2.0.42): https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest, if you have already installed the azure cli, please upgrade the version to latest version.
2. Create an azure kubernetes cluster with default default parameter and a specified group name and kubernetes cluster name and dns name, these names will be used later.
![alt text](https://docs.microsoft.com/en-us/azure/dev-spaces/media/common/kubernetes-create-cluster-2.png)
3. in console , run `az login` and  `az account set --subscritpion=XXXXXXX` to switch to the subscription where the kubernetes cluster created.
4. if you previously installed azure dev-spaces cli, please uninstall it.
5. in terminal run `az aks use-dev-spaces -g g -n n`, and install latest azure dev-spaces cli with the hint in console
6. When `An Azure Dev Spaces Controller will be created that targets resource 'n' in resource group 'g'. Continue? (y/N):` hint appear, input 'N' since the group name and cluster name in the command line is wrong on purpose.
7. Remove all the files and folder under `C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI (Preview)`, copy all the files in `\\devdivcn\Shared\Personal\andxu\bugbash\AzdsCli-PrivateBuild` to this folder.
8. Open a new terminal: run `azds --version`,make sure the following version is print:
`Z:\Personal\andxu\bugbash\AzdsCli-PrivateBuild>azds --version
Azure Dev Spaces CLI (Preview)
0.1.0.07191646-stephpr`
9. Install the latest vscode, install extension: "Language support for Java", in vscode settings by ctrl + comma, add the following settings
`"extensions.autoUpdate": false`
10. install the vscode extension by the vsix in `\\devdivcn\Shared\Personal\andxu\bugbash\azds-0.1.1.vsix`
11. install the vscode extension by the vsix in `\\devdivcn\Shared\Personal\andxu\bugbash\vscode-java-debugger-azds-0.1.0.vsix`

12. add system environment variable: `AZDS_ENVIRONMENT=dev`
![image](https://user-images.githubusercontent.com/17075863/43057509-544c68d6-8e75-11e8-9a99-2bda5445e46b.png)

13. Start a new terminal, run	`azds controller create -g <your resouce group name> -n <your kubernetes cluster name> -tg <your resouce group name> -tn <your kubernetes cluster name>`. When this terminal finishes, run `azds controller select -g <your resouce group name> -n <your kubernetes cluster name>` and then run `azds space select` and input `1` for the default space name.
	
14. clone the git to a directory: `https://github.com/stepro/dev-spaces` and open the folder `samples\java\getting-started\webfrontend` in vscode
15. In vscode, run the command by ctrl+shift+p: `Azure Dev Spaces: prepare configuration files ...`
16. Set a breakpoint at `samples\java\getting-started\webfrontend\src\main\java\com\ms\sample\webfrontend\Application.java#line 19`, press F5, wait the breakpoint to be hit. 

**if step 15-17, if it passes, you can try any kind of maven projects(only  single pom.xml is now supported).**

**Comment by Eskibear** [comment]
Step 1: I've installed 2.0.10 before, unable to upgrade azure-cli to the latest.
```
$> brew update && brew upgrade azure-cli
Updated 1 tap (homebrew/core).
==> Updated Formulae
go-bindata                                                    libgphoto2                                                    pre-commit
Error: azure-cli 2.0.42 already installed

$> az --version
azure-cli (2.0.10)
```

Step 2 takes a lot of time.

At Step 5, fails due to az-cli version
```
$> az aks use-dev-spaces -g g -n n
az: error: argument _command_package: invalid choice: aks
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {appservice,managedapp,monitor,feedback,account,batch,functionapp,snapshot,acr,acs,sf,find,resource,ad,lock,image,vm,cdn,tag,mysql,disk,cloud,consumption,feature,storage,dla,group,billing,network,vmss,redis,logout,role,provider,dls,policy,postgres,cognitiveservices,lab,keyvault,iot,component,sql,configure,webapp,login,cosmosdb,interactive}
          ...
```

**Comment by Eskibear** [comment]
Step 5: please explain `g` and `n` 
```
Successfully installed Azure Dev Spaces (Preview) to /usr/local/bin/azds.

An Azure Dev Spaces Controller will be created that targets resource 'n' in resource group 'g'. Continue? (y/N): 
```

**Comment by Eskibear** [comment]
step 8
```
$> azds --version
Azure Dev Spaces CLI (Preview)
0.1.20180720.5
```
