### ISSUE TITLE
End game 0.2.0

### ISSUE THREAD

**Issue by andxu** [andxu/andy_doc#10]
# Build
- [x] 1/14 - Bump version to 0.2.0 @andxu
- [x] 1/14 - Add change log for 0.2.0 - @andxu
- [x] 1/14 - Signed RC Bits @andxu
https://vscjavaci.cloudapp.net/job/vscode-dev-spaces/job/vscode-java-debug-azds.vsix-withSign/

# Test
- [x] 1/14 - Run test plan on Windows and Mac https://github.com/andxu/andy_doc/issues/3 - @bsaby  
- [x] 1/14 - Run three multiple samples in https://github.com/andxu/samples - @andxu
- [x] 1/14 - Run webfrontend at https://github.com/Azure/dev-spaces/tree/master/samples/java/getting-started/webfrontend  - @andxu

# Tutorial && Document
- [x] 1/14 - Verify tutorial at https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-java @bsaby 
- [x] 1/14 - Verify tutorial at **https://docs.microsoft.com/en-us/azure/dev-spaces/team-development-java @bsaby 

# Release
- [x] 1/14 - Release tag 0.2.0 docker hub - @andxu
- [x] 1/14 - Add 0.2.0 tag for vscode-java-debug-azds - @andxu
- [x] 1/14 - Add 0.2.0 tag for java debug agent - @andxu
- [x] 1/14 - Release to marketplace  - @andxu

**Comment by sallyur** [comment]
### Run test plan on Windows

**Issues**
One new issue recorded in onenote issue [2](#2  (Web view))
Known issue "Call three times effective pom request when prepare azds files" and "It will pop out automatically if reopen project in vscode" also repro, recorded in onenote issue [1](#1  (Web view))

**Build** 
54

**Configuration**
1.	Java: 1.8.0_191
2.	Vscode: 1.29.1
3.	Azure-cli: 2.0.52
4.	Azure-cli extension-dev-spaces-preview: 0.1.6
5.	Azure Dev Spaces CLI (Preview): 0.1.20181128.7
6.	Vscode extension: 
•	Azure Dev Spaces: 0.1.20181128
•	Remote debug: 0.2.0
7.	Environment: 
•	production

**Test result**

Test case | Windows
-- | --
HelloWorld | Pass
Variables | Pass
Big stack frame | Pass
Breakpoint and inner class | Pass
No debug information test | Pass
Variable Perform Test | >5s (7-8s)
PetClinic | Pass
Odd names | Pass
Multiple Models - jar with dependency | Pass
Multiple Models - Spring boot | Pass
Multiple Models - onejar | Pass
Multiple Models - mvn jar | Pass
Multiple Models - mvn exec | Pass
Multiple Models - Spring boot multiple module | Pass
Tutorial Sample-Webfrontend | Pass
Test classpath and runtime scope dependency | Pass

**Comment by sallyur** [comment]
### Run test plan on Mac
**Issues**
One new issue recorded in onenote issue [2](#2  (Web view))
Known issue "Call three times effective pom request when prepare azds files" and "It will pop out automatically if reopen project in vscode" also repro, recorded in onenote issue [1](#1  (Web view))

**Build**
54

**Configuration**

Java: 1.8.0_191
Vscode: 1.29.1
Azure-cli: 2.0.52
Azure-cli extension-dev-spaces-preview: 0.1.6
Azure Dev Spaces CLI (Preview): 0.1.20181128.7
Vscode extension:
•	Azure Dev Spaces: 0.1.20181128
•	Remote debug: 0.2.0
Environment:
•	production

**Test result**

Test case | Mac
-- | --
HelloWorld | Pass
Variables | Pass
Big stack frame | Pass
Breakpoint and inner class | Pass
No debug information test | Pass
Variable Perform Test | Pass
PetClinic | Pass
Odd names | Pass
Multiple Models - jar with dependency | Pass
Multiple Models - Spring boot | Pass
Multiple Models - onejar | Pass
Multiple Models - mvn jar | Pass
Multiple Models - mvn exec | Pass
Multiple Models - Spring boot multiple module | Pass
Tutorial Sample-Webfrontend | Pass
Test classpath and runtime scope dependency | Pass

**Comment by sallyur** [comment]
### Run test plan on Windows
### Open bug
#11 
### Configuration

```
1. Java: 1.8.0_191
2. Vscode: 1.30.2
3. Azure-cli: 2.0.54
4. Azure-cli extension-dev-spaces-preview: 0.1.6
5. Azure Dev Spaces CLI (Preview): 0.1.20190102.6
6. Vscode extension:
   Azure Dev Spaces: 0.1.20190102
   Remote debug: 0.2.0
7. Environment:
    production
```

### Test result
Test case | Windows
-- | --
HelloWorld | Pass
Variables | Pass
Big stack frame | Pass
Breakpoint and inner class | Pass
No debug information test | Pass
Variable Perform Test | >5s (7-8s)
PetClinic | Pass
Odd names | Pass
Multiple Models - jar with dependency | Pass
Multiple Models - Spring boot | Pass
Multiple Models - onejar | Pass
Multiple Models - mvn jar | Pass
Multiple Models - mvn exec | Pass
Multiple Models - Spring boot multiple module | Pass
Tutorial Sample-Webfrontend | Pass
Test classpath and runtime scope dependency | Pass

**Comment by sallyur** [comment]
### Run test plan on Mac
### Open bug
#11
### Build 
61
### Configuration
```
1.Java: 1.8.0_191
2. Vscode: 1.30.2
3. Azure-cli: 2.0.54
4. Azure-cli extension-dev-spaces-preview: 0.1.6
5. Azure Dev Spaces CLI (Preview): 0.1.20190102.6
6. Vscode extension:
   Azure Dev Spaces: 0.1.20190102
   Remote debug: 0.2.0
7. Environment:
    production
```

Test case | Mac
-- | --
HelloWorld | Pass
Variables | Pass
Big stack frame | Pass
Breakpoint and inner class | Pass
No debug information test | Pass
Variable Perform Test | Pass
PetClinic | Pass
Odd names | Pass
Multiple Models - jar with dependency | Pass
Multiple Models - Spring boot | Pass
Multiple Models - onejar | Pass
Multiple Models - mvn jar | Pass
Multiple Models - mvn exec | Pass
Multiple Models - Spring boot multiple module | Pass
Tutorial Sample-Webfrontend | Pass
Test classpath and runtime scope dependency | Pass
