### ISSUE TITLE
Call two times effective pom request when prepare azds files

### ISSUE THREAD

**Issue by sallyur** [andxu/andy_doc#11]
**Environment:**

- Operating System: Win10/Mac OS

- JDK version: 1.8.0_191

- Visual Studio Code version: 1.30.2

- Azure cli: 2.0.54

- Azure Dev Spaces CLI (Preview): 0.1.20190102.6

- Build: 61

**Repro steps:**

1. Open one test project

2. F1 and select "AZDS: Prepare xxxx"

**Result:**
After selecting the base image for the first time, after a while, it will will let you choose again
![image](https://user-images.githubusercontent.com/28860891/51102925-bddbe800-181b-11e9-8ae7-97b69959f195.png)

**Comment by andxu** [comment]
logged in tfs : https://devdiv.visualstudio.com/DevDiv/_queries/query/36382b31-b487-4a9d-8581-f39f182efa67/

**Comment by andxu** [comment]
Fixed.
