### ISSUE TITLE
VS Code Java Debugger for Azure Dev Spaces End Game 0.1.0

### ISSUE THREAD

**Issue by andxu** [andxu/andy_doc#4]
Preparation:
1. set env variable: AZDS_ENVIRONMENT=staging
2.  install staging azds-cli:
CLI: [Azure Dev Spaces CLI.exe](https://mindarostage.blob.core.windows.net/azdssetup/LKS/Azure%20Dev%20Spaces%20CLI.exe)
OSX Setup: https://mindarostage.blob.core.windows.net/azdssetup/LKS/azds-osx-setup.sh  
Linux Setup: https://mindarostage.blob.core.windows.net/azdssetup/LKS/azds-linux-setup.sh
3. install vscode plugin at  https://mindarostage.blob.core.windows.net/azdssetup/LKS/azds-0.1.1.vsix
4. install vscode plugin at https://vscjavaci.cloudapp.net/job/vscode-java-debug-azds.vsix-withSign/27/Azure/processDownloadRequest/signedartifacts/27/vscode-java-debugger-azds-0.1.0.vsix
5. create azure kubernetes cluster and install dev-spaces using `az aks use-dev-spaces -g <your resouce group name> -n <your kubernetes cluster name>`
6. open the java project in vscode:  https://github.com/Azure/dev-spaces/tree/master/samples/java/getting-started/webfrontend
7. In vscode, run the command by ctrl+shift+p: `Azure Dev Spaces: prepare configuration files ...`
8. Set a breakpoint at `samples\java\getting-started\webfrontend\src\main\java\com\ms\sample\webfrontend\Application.java#line 19`, press F5, wait the breakpoint to be hit.

**Comment by testforstephen** [comment]
# Coverage test for different maven docker images

Covered the following maven docker image.
- maven: 3.5-jdk-8-slim  **PASSED**
- maven: 3.5-jdk-8 **PASSED**
- maven: 3.5-jdk-8-alpine **FAILED**
- maven: 3.5-jdk-10-slim **PASSED**
- maven: 3.5-jdk-10 **PASSED**

**Comment by bsaby** [comment]
### Run test plan on Windows and Mac #3 
**Configuration:**
```
1. Java: oracle jdk8
2. Vscode 1.25.1
3. azure-cli: 2.0.43
   Azure-cli extension-dev-spaces-preview: 0.1.6
4. azds-cli: Azure Dev Spaces CLI (Preview): 0.1.20180731.3
5. Vscode extension: 
	• Azure Dev Spaces: 0.1.120180731
	• Remote debug: 0.1.0
6. Environment: AZDS_ENVIRONMENT=staging
7. OS: Windows/Mac 
```

**Issues:**

1. NoSourceTest: [#12](https://github.com/andxu/andy_remote/issues/12) Run failed with error  `Exception in thread "main" java .lang.NoClassDefFoundError: org/apache/commons/io/IOUtils` 
2. VariablePerformTest: The time for variable expanding is more than 5s (8s-10s)

**Test result:**

Test case | Windows | Mac
-- | -- | --
HelloWorld | Pass | Pass
Variables | Pass | Pass
Big   stack frame | Pass | Pass
Breakpoint   and inner class | Pass | Pass
No   debug information test | **Failed [#12](https://github.com/andxu/andy_remote/issues/12)** | **Failed [#12](https://github.com/andxu/andy_remote/issues/12)**
Variable   Perform Test | Pass | Pass
PetClinic | Pass | Pass
Odd   names | Pass | Pass
Webfrontend | Pass | Pass

**Comment by andxu** [comment]
### Run test plan on Windows 
```
1. Java: oracle jdk10
2. Vscode 1.25.1
3. azure-cli: 2.0.43
   Azure-cli extension-dev-spaces-preview: 0.1.6
4. azds-cli: Azure Dev Spaces CLI (Preview): 0.1.20180731.3
5. Vscode extension: 
	• Azure Dev Spaces: 0.1.120180731
	• Remote debug: 0.1.0
6. Environment: AZDS_ENVIRONMENT=staging
7. OS: Windows/
```

Run tests:
modified code of webfrontend to connect mywebapi.
BreakPointTest
Hello$orld
CustomClassLoaderTest

**Comment by andxu** [comment]
### Run test plan on Ubuntu 18.04 LTS

```
1. Java: oracle jdk"1.8.0_181"
2. Vscode 1.25.1
3. azure-cli: 2.0.43
   Azure-cli extension-dev-spaces-preview: 0.1.6
4. azds-cli: Azure Dev Spaces CLI (Preview): 0.1.20180731.3
5. Vscode extension: 
	• Azure Dev Spaces: 0.1.120180731
	• Remote debug: 0.1.0
6. Environment: AZDS_ENVIRONMENT=staging
7. OS: Windows/
```

Run tests:
webfrontend  **pass**
mywebapi .**pass**

**Comment by andxu** [comment]
### Run test plan on Mac

```
1. Java: oracle jdk"1.8.0_181"
2. Vscode 1.25.1
3. azure-cli: 2.0.43
   Azure-cli extension-dev-spaces-preview: 0.1.6
4. azds-cli: Azure Dev Spaces CLI (Preview): 0.1.20180731.3
5. Vscode extension: 
	• Azure Dev Spaces: 0.1.120180731
	• Remote debug: 0.1.0
6. Environment: AZDS_ENVIRONMENT=staging
7. OS: MacOs
```

Run tests:
webfrontend  **pass**
