### ISSUE TITLE
Azds Java End Game 0.1.2

### ISSUE THREAD

**Issue by andxu** [andxu/andy_doc#5]
Preparation:
1. verify there is no env variable: AZDS_ENVIRONMENT
```
C:\Users\andxu>echo %AZDS_ENVIRONMENT%
%AZDS_ENVIRONMENT%
```
2.  install latest azure cli, uninstall Azure AZDS cli if you installed.
3. install latest azds vscode plugin
4. install azds java debugger plugin at https://vscjavaci.cloudapp.net/job/vscode-java-debug-azds.vsix-withSign for the version 0.1.2
5. create azure kubernetes cluster and install dev-spaces using `az aks use-dev-spaces -g <your resouce group name> -n <your kubernetes cluster name>`
6. Run test plan at https://github.com/andxu/andy_doc/issues/3

**Comment by andxu** [comment]
# Build
- [ ] 9/18 - Bump version to 0.1.2 @andxu
- [ ] 9/18 - Add change log for 0.1.2 - @andxu
- [ ] 9/18 - Signed RC Bits @andxu
https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/

# Test
- [ ] 9/18 - Run test plan on Windows and Mac https://github.com/andxu/andy_doc/issues/3 - @bsaby  
- [ ] 9/18 - Run  - @andxu

# Tutorial && Document
- [ ] 9/18 - Verify tutorial at https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-java @bsaby 
- [ ] 9/18 - Verify tutorial at **https://docs.microsoft.com/en-us/azure/dev-spaces/team-development-java @bsaby 

# Release
- [x] 9/18 - Release tag 0.1.2 docker hub - @andxu
- [ ] 9/18 - Add 0.1.2 tag for vscode-java-debug-azds - @andxu
- [ ] 9/18 - Add 0.1.2 tag for java debug agent - @andxu
- [ ] 9/18 - Release to marketplace  - @andxu

**Comment by sallyur** [comment]
### Run test plan on Windows

**Configuration:**
1. Java: oracle jdk8
2. Vscode 1.27.2
3. azure-cli: 2.0.45
   Azure-cli extension-dev-spaces-preview: 0.1.6
4. azds-cli: Azure Dev Spaces CLI (Preview): 0.1.20180906.11
5. Vscode extension: 
	• Azure Dev Spaces: 0.1.120180906
	• Remote debug: 0.1.2
6. Environment: Product

**Test result:**

Test   case | Windows
-- | --
HelloWorld | Pass
Variables | Pass
Big   stack frame | Pass
Breakpoint   and inner class | Pass
No debug   information test | Pass
Variable   Perform Test | Pass
PetClinic | Pass
Odd   names | Pass
Multiple Models - jar with dependency | Pass
Multiple Models - Spring boot | Pass
Multiple Models - onejar | Pass
Multiple Models - mvn jar | Pass
Multiple Models - mvn exec | Pass
Multiple Models - Spring boot multiple module | Pass
Webfrontend | Pass
Test classpath and runtime scope dependency | Pass

**Comment by sallyur** [comment]
### Run test plan on Mac

**Configuration:**

Java: oracle jdk8
Vscode 1.27.2
azure-cli: 2.0.45
Azure-cli extension-dev-spaces-preview: 0.1.6
azds-cli: Azure Dev Spaces CLI (Preview): 0.1.20180906.11
Vscode extension:
• Azure Dev Spaces: 0.1.120180906
• Remote debug: 0.1.2
Environment: Product

Run tests:
Webfrontend Pass
