### ISSUE TITLE
azds java debugger 0.1.3 Endgame

### ISSUE THREAD

**Issue by andxu** [andxu/andy_doc#7]
# Build
- [x] 9/29 - Bump version to 0.1.3 @andxu
- [x] 9/29 - Add change log for 0.1.3 - @andxu
- [x] 9/29 - Signed RC Bits @andxu
https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/

# Test
- [x] 9/30 - Run test plan on Windows and Mac https://github.com/andxu/andy_doc/issues/3 - @bsaby  
- [x] 9/30 - Run three multiple samples in https://github.com/andxu/samples - @andxu
- [x] 9/30 - Run webfrontend at https://github.com/Azure/dev-spaces/tree/master/samples/java/getting-started/webfrontend  - @andxu

# Tutorial && Document
- [x] 9/30 - Verify tutorial at https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-java @bsaby 
- [x] 9/30 - Verify tutorial at **https://docs.microsoft.com/en-us/azure/dev-spaces/team-development-java @bsaby 

# Release
- [x] 9/29 - Release tag 0.1.3 docker hub - @andxu
- [x] 9/30 - Add 0.1.3 tag for vscode-java-debug-azds - @andxu
- [x] 9/30 - Add 0.1.3 tag for java debug agent - @andxu
- [x] 9/30 - Release to marketplace  - @andxu

**Comment by bsaby** [comment]
### Run test plan on Windows
Configuration:
```
1. Java: oracle jdk 1.8.0_181
2. Vscode: 1.27.2
3. azure-cli: 2.0.46
   azure-cli extension-dev-spaces-preview: 0.1.6
    Azure Dev Spaces CLI (Preview): 0.1.20180919.5
4. Vscode extension: 
    Azure Dev Spaces:   0.1.20180919
    Java Debugger for Azure Dev Sapces: 0.1.3
```
Test result:

Test case | Windows
-- | --
HelloWorld | Pass
Variables | Pass
Big   stack frame | Pass
Breakpoint   and inner class | Pass
No   debug information test | Pass
Variable   Perform Test | >5s (7-8s)
PetClinic | Pass
Odd   names | Pass
Multiple   Models - jar with dependency | [Onenote issue: #3](https://microsoft.sharepoint.com/teams/WPTFundamental/_layouts/OneNote.aspx?id=%2Fteams%2FWPTFundamental%2FShared%20Documents%2FAAPTServicing%2FAAPT%20Webtools%20Offshore%20Current%20Release&wd=target%28Java%20Tools%2FVscode%20Extensions%2FVscdoe%20Remote%20debug.one%7CCC285EBA-2318-4068-A030-472C6A58EBFC%2F9%5C%2F30%20-%20Endgame%7C50A3D2DE-B528-4868-BC11-F9BC4AD377D6%2F%29onenote:https://microsoft.sharepoint.com/teams/WPTFundamental/Shared%20Documents/AAPTServicing/AAPT%20Webtools%20Offshore%20Current%20Release/Java%20Tools/Vscode%20Extensions/Vscdoe%20Remote%20debug.one#9/30%20-%20Endgame%20&section-id={CC285EBA-2318-4068-A030-472C6A58EBFC}&page-id={50A3D2DE-B528-4868-BC11-F9BC4AD377D6}&object-id={B680968A-808A-0856-19DA-85351A68EC4F}&4E)
Multiple   Models - Spring boot | Pass
Multiple   Models - onejar | Pass
Multiple   Models - mvn jar | Pass
Multiple   Models - mvn exec | Pass
Multiple   Models - Spring boot multiple module | Pass
Tutorial   Sample-Webfrontend | Pass
Test   classpath and runtime scope dependency | [Onenote issue: #4](https://microsoft.sharepoint.com/teams/WPTFundamental/_layouts/OneNote.aspx?id=%2Fteams%2FWPTFundamental%2FShared%20Documents%2FAAPTServicing%2FAAPT%20Webtools%20Offshore%20Current%20Release&wd=target%28Java%20Tools%2FVscode%20Extensions%2FVscdoe%20Remote%20debug.one%7CCC285EBA-2318-4068-A030-472C6A58EBFC%2F9%5C%2F30%20-%20Endgame%7C50A3D2DE-B528-4868-BC11-F9BC4AD377D6%2F%29onenote:https://microsoft.sharepoint.com/teams/WPTFundamental/Shared%20Documents/AAPTServicing/AAPT%20Webtools%20Offshore%20Current%20Release/Java%20Tools/Vscode%20Extensions/Vscdoe%20Remote%20debug.one#9/30%20-%20Endgame%20&section-id={CC285EBA-2318-4068-A030-472C6A58EBFC}&page-id={50A3D2DE-B528-4868-BC11-F9BC4AD377D6}&object-id={B680968A-808A-0856-19DA-85351A68EC4F}&44)

**Comment by bsaby** [comment]
### Run test plan on Mac
Debug project failed : [#6](https://microsoft.sharepoint.com/teams/WPTFundamental/_layouts/OneNote.aspx?id=%2Fteams%2FWPTFundamental%2FShared%20Documents%2FAAPTServicing%2FAAPT%20Webtools%20Offshore%20Current%20Release&wd=target%28Java%20Tools%2FVscode%20Extensions%2FVscdoe%20Remote%20debug.one%7CCC285EBA-2318-4068-A030-472C6A58EBFC%2F9%5C%2F30%20-%20Endgame%7C50A3D2DE-B528-4868-BC11-F9BC4AD377D6%2F%29onenote:https://microsoft.sharepoint.com/teams/WPTFundamental/Shared%20Documents/AAPTServicing/AAPT%20Webtools%20Offshore%20Current%20Release/Java%20Tools/Vscode%20Extensions/Vscdoe%20Remote%20debug.one#9/30%20-%20Endgame%20&section-id={CC285EBA-2318-4068-A030-472C6A58EBFC}&page-id={50A3D2DE-B528-4868-BC11-F9BC4AD377D6}&object-id={5E3F216F-CEE4-00F8-1D8D-100FA1F9ADA2}&6D), 
Try the previous marketplace version: 0.1.2, meet the same issue.
