### ISSUE TITLE
AZDS Java Endgame 0.1.4

### ISSUE THREAD

**Issue by andxu** [andxu/andy_doc#9]
# Build
- [x] 11/7 - Bump version to 0.1.4 @andxu
- [x] 11/7 - Add change log for 0.1.4 - @andxu
- [x] 11/7 - Signed RC Bits @andxu
https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/

# Test
- [x] 11/7 - Run test plan on Windows and Mac https://github.com/andxu/andy_doc/issues/3 - @bsaby  
- [x] 11/7 - Run three multiple samples in https://github.com/andxu/samples - @andxu
- [x] 11/7 - Run webfrontend at https://github.com/Azure/dev-spaces/tree/master/samples/java/getting-started/webfrontend  - @andxu

# Tutorial && Document
- [x] 11/7 - Verify tutorial at https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-java @bsaby 
- [x] 11/7 - Verify tutorial at **https://docs.microsoft.com/en-us/azure/dev-spaces/team-development-java @bsaby 

# Release
- [x] 11/7 - Release tag 0.1.4 docker hub - @andxu
- [x] 11/7 - Add 0.1.4 tag for vscode-java-debug-azds - @andxu
- [x] 11/7 - Add 0.1.4 tag for java debug agent - @andxu
- [x] 11/7 - Release to marketplace  - @andxu

**Comment by ZhengJun003** [comment]
### Run test plan on Mac
**Configuration:**

1. Java: oracle jdk8
2. Vscode 1.28.2
3. azure-cli: 2.0.50
    Azure-cli extension-dev-spaces-preview: 0.1.6
4. azds-cli: Azure Dev Spaces CLI (Preview): 0.1.20181023.7
5. Vscode extension:
• Azure Dev Spaces: 0.1.120181023
• Remote debug: 0.1.4
6. Environment: Production

**Test Result:**


Test case | Mac
-- | --
Variable Perform Test | Pass
Multiple Models - jar with dependency | Pass
Multiple Models - Spring boot | Pass
Webfrontend | Pass
